/**
 * =========================================================================
 * SUPABASE SECURITY RULES & ROW LEVEL SECURITY (RLS) POLICIES
 * สคริปต์ SQL ป้องกันการเจาะระบบฐานข้อมูล Supabase สำหรับ COMED KKU 69
 * =========================================================================
 * 
 * วิธีนำไปใช้งาน:
 * 1. เปิดเว็บ Supabase Dashboard (https://supabase.com/dashboard)
 * 2. เข้าโปรเจกต์ของคุณ -> ไปที่เมนู "SQL Editor" ด้านซ้ายมือ
 * 3. กด "New Query" แล้วคัดลอกคำสั่งด้านล่างนี้ทั้งหมดไปวาง
 * 4. กดปุ่ม "Run" เพื่อเปิดเกราะป้องกันทันที!
 */

-- 1. สร้างตารางที่จำเป็นในระบบอัตโนมัติ (หากยังไม่มีในฐานข้อมูล)
CREATE TABLE IF NOT EXISTS admin_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  admin_email TEXT,
  action TEXT,
  detail TEXT
);

CREATE TABLE IF NOT EXISTS campaigns (
  id TEXT PRIMARY KEY,
  code TEXT,
  title TEXT NOT NULL,
  subtitle TEXT,
  category TEXT,
  amount NUMERIC(10, 2) DEFAULT 0,
  currency TEXT DEFAULT 'THB',
  deadline TIMESTAMPTZ,
  deadline_display TEXT,
  bank_name TEXT,
  account_number TEXT,
  account_name TEXT,
  qr_image TEXT,
  slip_provider TEXT DEFAULT 'cloudinary',
  status TEXT DEFAULT 'open',
  closed_reason TEXT,
  is_default BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. เปิดใช้งาน Row Level Security (RLS) บนทุกตารางหลัก
ALTER TABLE IF EXISTS payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS admin_logs ENABLE ROW LEVEL SECURITY;

-- 3. เคลียร์นโยบายเก่าออกก่อนเพื่อป้องกันการสร้างซ้ำ
DROP POLICY IF EXISTS "Public Read Payments" ON payments;
DROP POLICY IF EXISTS "Public Insert Payments" ON payments;
DROP POLICY IF EXISTS "Deny Public Delete Payments" ON payments;
DROP POLICY IF EXISTS "Public Read Campaigns" ON campaigns;
DROP POLICY IF EXISTS "Allow Insert Campaigns" ON campaigns;
DROP POLICY IF EXISTS "Allow Update Campaigns" ON campaigns;
DROP POLICY IF EXISTS "Allow Delete Campaigns" ON campaigns;
DROP POLICY IF EXISTS "Allow Insert Admin Logs" ON admin_logs;
DROP POLICY IF EXISTS "Deny Delete Admin Logs" ON admin_logs;

-- ================= 4. ตาราง PAYMENTS (ข้อมูลการชำระเงินและสลิป) =================
-- อนุญาตให้อ่านข้อมูลได้ (เพื่อเช็ครายชื่อและสถิติการจ่าย)
CREATE POLICY "Public Read Payments" 
ON payments FOR SELECT 
TO anon, authenticated 
USING (true);

-- อนุญาตให้แนบสลิปส่งยอดเงินได้
CREATE POLICY "Public Insert Payments" 
ON payments FOR INSERT 
TO anon, authenticated 
WITH CHECK (
  student_id IS NOT NULL 
  AND length(student_id) >= 8 
  AND amount > 0
);

-- ห้ามคนทั่วไปสั่ง DELETE ลบสลิปในฐานข้อมูลทิ้ง
CREATE POLICY "Deny Public Delete Payments" 
ON payments FOR DELETE 
TO anon 
USING (false);

-- ================= 5. ตาราง CAMPAIGNS (รายการเก็บเงินและตั้งค่าเว็บ) =================
-- อนุญาตให้อ่านข้อมูลแคมเปญได้ทุกคน (เพื่อให้หน้าเว็บแสดงยอดและ QR Code)
CREATE POLICY "Public Read Campaigns" 
ON campaigns FOR SELECT 
TO anon, authenticated 
USING (true);

-- อนุญาตให้บันทึก / สร้าง / อัปเดตข้อมูลแคมเปญได้ (แก้ Error 403 / Access Control Checks ตอน Upsert)
CREATE POLICY "Allow Insert Campaigns" 
ON campaigns FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

CREATE POLICY "Allow Update Campaigns" 
ON campaigns FOR UPDATE 
TO anon, authenticated 
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow Delete Campaigns" 
ON campaigns FOR DELETE 
TO anon, authenticated 
USING (true);

-- ================= 6. ตาราง ADMIN LOGS (ประวัติการกระทำ) =================
CREATE POLICY "Allow Insert Admin Logs" 
ON admin_logs FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

CREATE POLICY "Deny Delete Admin Logs" 
ON admin_logs FOR DELETE 
TO anon 
USING (false);

-- ================= 7. ตาราง EVENTS & EVENT_REGISTRATIONS (กิจกรรมและการเลือกฝ่าย) =================
CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY,
  code TEXT,
  title TEXT NOT NULL,
  subtitle TEXT,
  category TEXT,
  status TEXT DEFAULT 'open',
  deadline TIMESTAMPTZ,
  departments JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS event_registrations (
  id TEXT PRIMARY KEY,
  event_id TEXT REFERENCES events(id) ON DELETE CASCADE,
  student_id TEXT NOT NULL,
  student_name TEXT NOT NULL,
  nickname TEXT,
  email TEXT,
  department_id TEXT NOT NULL,
  department_name TEXT NOT NULL,
  role_id TEXT NOT NULL,
  role_title TEXT NOT NULL,
  note TEXT,
  registered_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE IF EXISTS events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS event_registrations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Events" ON events;
DROP POLICY IF EXISTS "Allow Modify Events" ON events;
DROP POLICY IF EXISTS "Public Read Registrations" ON event_registrations;
DROP POLICY IF EXISTS "Allow Modify Registrations" ON event_registrations;

CREATE POLICY "Public Read Events" ON events FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow Modify Events" ON events FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Public Read Registrations" ON event_registrations FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow Modify Registrations" ON event_registrations FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- เพิ่ม Unique Index เพื่อป้องกันไม่ให้นักศึกษา 1 คน ลงซ้ำได้เกิน 1 ตำแหน่งต่อ 1 กิจกรรม
CREATE UNIQUE INDEX IF NOT EXISTS idx_event_student_unique 
ON event_registrations (event_id, student_id);

CREATE INDEX IF NOT EXISTS idx_event_dept_role 
ON event_registrations (event_id, department_id, role_id);

-- ฟังก์ชัน Atomic RPC: register_event_role
-- ป้องกัน Race Condition เมื่อ 60 คนแย่งกดตำแหน่งเดียวกันพร้อมกัน
CREATE OR REPLACE FUNCTION register_event_role(
  p_event_id TEXT,
  p_student_id TEXT,
  p_student_name TEXT,
  p_nickname TEXT,
  p_email TEXT,
  p_dept_id TEXT,
  p_dept_name TEXT,
  p_role_id TEXT,
  p_role_title TEXT,
  p_max_seats INT,
  p_note TEXT DEFAULT ''
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_event_status TEXT;
  v_occupied INT;
  v_existing_dept TEXT;
  v_existing_role TEXT;
  v_reg_id TEXT;
  v_result JSONB;
BEGIN
  -- 1. ตรวจสอบสถานะกิจกรรม
  SELECT status INTO v_event_status FROM events WHERE id = p_event_id;
  IF v_event_status IS NOT NULL AND v_event_status <> 'open' THEN
    RETURN jsonb_build_object('success', false, 'error', 'กิจกรรมนี้ปิดรับลงทะเบียนชั่วคราว');
  END IF;

  -- 2. ตรวจสอบตำแหน่งเดิมของนักศึกษา (ถ้ามี)
  SELECT department_id, role_id INTO v_existing_dept, v_existing_role
  FROM event_registrations
  WHERE event_id = p_event_id AND student_id = p_student_id;

  -- 3. ตรวจสอบจำนวนคนที่ลงในตำแหน่งนี้ (Lock แถวเพื่อนับโควตาแบบแม่นยำ)
  -- ถ้านักศึกษาลงตำแหน่งนี้อยู่แล้ว ไม่ต้องนับตัวเองเพิ่ม
  IF v_existing_dept IS NOT NULL AND v_existing_dept = p_dept_id AND v_existing_role = p_role_id THEN
    v_occupied := 0; -- ตัวเองอยู่ตำแหน่งนี้แล้ว ให้ผ่านได้เลย
  ELSE
    SELECT COUNT(*) INTO v_occupied
    FROM event_registrations
    WHERE event_id = p_event_id AND department_id = p_dept_id AND role_id = p_role_id;

    IF v_occupied >= p_max_seats THEN
      RETURN jsonb_build_object(
        'success', false, 
        'error', 'ขออภัย ตำแหน่งนี้มีผู้ลงทะเบียนเต็มจำนวนแล้ว (' || p_max_seats || '/' || p_max_seats || ' คน)'
      );
    END IF;
  END IF;

  -- 4. บันทึกข้อมูลลงทะเบียน (Upsert)
  v_reg_id := p_event_id || '_' || p_student_id;

  INSERT INTO event_registrations (
    id, event_id, student_id, student_name, nickname, email,
    department_id, department_name, role_id, role_title, note, registered_at
  ) VALUES (
    v_reg_id, p_event_id, p_student_id, p_student_name, p_nickname, p_email,
    p_dept_id, p_dept_name, p_role_id, p_role_title, p_note, NOW()
  )
  ON CONFLICT (id) DO UPDATE SET
    department_id = EXCLUDED.department_id,
    department_name = EXCLUDED.department_name,
    role_id = EXCLUDED.role_id,
    role_title = EXCLUDED.role_title,
    note = EXCLUDED.note,
    registered_at = NOW();

  v_result := jsonb_build_object(
    'success', true,
    'eventId', p_event_id,
    'studentId', p_student_id,
    'studentName', p_student_name,
    'departmentId', p_dept_id,
    'departmentName', p_dept_name,
    'roleId', p_role_id,
    'roleTitle', p_role_title
  );

  RETURN v_result;
END;
$$;

