/**
 * =========================================================================
 * SUPABASE SECURITY RULES & ROW LEVEL SECURITY (RLS) POLICIES
 * สคริปต์ SQL ป้องกันการเจาะระบบฐานข้อมูล Supabase สำหรับ COMED KKU 69
 * =========================================================================
 * 
 * วิธีนำไปใช้งาน:
 * 1. เปิดเว็บ Supabase Dashboard (https://supabase.com/dashboard)
 * 2. เข้าโปรเจกต์ของคุณ -> ไปที่เมนู "SQL Editor" ด้านซ้ายมือ
 * 3. กด "New Query" แล้วคัดลอกคำสั่งด้านล่างนี้ทั้งหมดไปวาง
 * 4. กดปุ่ม "Run" เพื่อเปิดเกราะป้องกันทันที!
 */

-- 1. สร้างตารางที่จำเป็นในระบบอัตโนมัติ (หากยังไม่มีในฐานข้อมูล)
CREATE TABLE IF NOT EXISTS admin_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  admin_email TEXT,
  action TEXT,
  detail TEXT
);

CREATE TABLE IF NOT EXISTS campaigns (
  id TEXT PRIMARY KEY,
  code TEXT,
  title TEXT NOT NULL,
  subtitle TEXT,
  category TEXT,
  amount NUMERIC(10, 2) DEFAULT 0,
  currency TEXT DEFAULT 'THB',
  deadline TIMESTAMPTZ,
  deadline_display TEXT,
  bank_name TEXT,
  account_number TEXT,
  account_name TEXT,
  qr_image TEXT,
  slip_provider TEXT DEFAULT 'cloudinary',
  status TEXT DEFAULT 'open',
  closed_reason TEXT,
  is_default BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. เปิดใช้งาน Row Level Security (RLS) บนทุกตารางหลัก
ALTER TABLE IF EXISTS payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS admin_logs ENABLE ROW LEVEL SECURITY;

-- 3. เคลียร์นโยบายเก่าออกก่อนเพื่อป้องกันการสร้างซ้ำ
DROP POLICY IF EXISTS "Public Read Payments" ON payments;
DROP POLICY IF EXISTS "Public Insert Payments" ON payments;
DROP POLICY IF EXISTS "Deny Public Delete Payments" ON payments;
DROP POLICY IF EXISTS "Public Read Campaigns" ON campaigns;
DROP POLICY IF EXISTS "Allow Insert Campaigns" ON campaigns;
DROP POLICY IF EXISTS "Allow Update Campaigns" ON campaigns;
DROP POLICY IF EXISTS "Allow Delete Campaigns" ON campaigns;
DROP POLICY IF EXISTS "Allow Insert Admin Logs" ON admin_logs;
DROP POLICY IF EXISTS "Deny Delete Admin Logs" ON admin_logs;

-- ================= 4. ตาราง PAYMENTS (ข้อมูลการชำระเงินและสลิป) =================
-- อนุญาตให้อ่านข้อมูลได้ (เพื่อเช็ครายชื่อและสถิติการจ่าย)
CREATE POLICY "Public Read Payments" 
ON payments FOR SELECT 
TO anon, authenticated 
USING (true);

-- อนุญาตให้แนบสลิปส่งยอดเงินได้
CREATE POLICY "Public Insert Payments" 
ON payments FOR INSERT 
TO anon, authenticated 
WITH CHECK (
  student_id IS NOT NULL 
  AND length(student_id) >= 8 
  AND amount > 0
);

-- ห้ามคนทั่วไปสั่ง DELETE ลบสลิปในฐานข้อมูลทิ้ง
CREATE POLICY "Deny Public Delete Payments" 
ON payments FOR DELETE 
TO anon 
USING (false);

-- ================= 5. ตาราง CAMPAIGNS (รายการเก็บเงินและตั้งค่าเว็บ) =================
-- อนุญาตให้อ่านข้อมูลแคมเปญได้ทุกคน (เพื่อให้หน้าเว็บแสดงยอดและ QR Code)
CREATE POLICY "Public Read Campaigns" 
ON campaigns FOR SELECT 
TO anon, authenticated 
USING (true);

-- อนุญาตให้บันทึก / สร้าง / อัปเดตข้อมูลแคมเปญได้ (แก้ Error 403 / Access Control Checks ตอน Upsert)
CREATE POLICY "Allow Insert Campaigns" 
ON campaigns FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

CREATE POLICY "Allow Update Campaigns" 
ON campaigns FOR UPDATE 
TO anon, authenticated 
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow Delete Campaigns" 
ON campaigns FOR DELETE 
TO anon, authenticated 
USING (true);

-- ================= 6. ตาราง ADMIN LOGS (ประวัติการกระทำ) =================
CREATE POLICY "Allow Insert Admin Logs" 
ON admin_logs FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

CREATE POLICY "Deny Delete Admin Logs" 
ON admin_logs FOR DELETE 
TO anon 
USING (false);

-- ================= 7. ตาราง EVENTS & EVENT_REGISTRATIONS (กิจกรรมและการเลือกฝ่าย) =================
CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY,
  code TEXT,
  title TEXT NOT NULL,
  subtitle TEXT,
  category TEXT,
  status TEXT DEFAULT 'open',
  deadline TIMESTAMPTZ,
  departments JSONB,
  tracks JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ปรับให้ตาราง events รองรับคอลัมน์ tracks ในกรณีสร้างตารางไปก่อนหน้านี้
ALTER TABLE events ADD COLUMN IF NOT EXISTS tracks JSONB;

CREATE TABLE IF NOT EXISTS event_registrations (
  id TEXT PRIMARY KEY,
  event_id TEXT REFERENCES events(id) ON DELETE CASCADE,
  student_id TEXT NOT NULL,
  student_name TEXT NOT NULL,
  nickname TEXT,
  email TEXT,
  phone TEXT,
  department_id TEXT NOT NULL,
  department_name TEXT NOT NULL,
  role_id TEXT NOT NULL,
  role_title TEXT NOT NULL,
  note TEXT,
  registered_at TIMESTAMPTZ DEFAULT NOW()
);

-- ปรับให้ตาราง event_registrations มีคอลัมน์ phone
ALTER TABLE event_registrations ADD COLUMN IF NOT EXISTS phone TEXT;

ALTER TABLE IF EXISTS events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS event_registrations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Events" ON events;
DROP POLICY IF EXISTS "Allow Modify Events" ON events;
DROP POLICY IF EXISTS "Public Read Registrations" ON event_registrations;
DROP POLICY IF EXISTS "Allow Modify Registrations" ON event_registrations;

CREATE POLICY "Public Read Events" ON events FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow Modify Events" ON events FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Public Read Registrations" ON event_registrations FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow Modify Registrations" ON event_registrations FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- Index ช่วยเพิ่มความเร็วในการค้นหาและจัดสรรตำแหน่ง
CREATE INDEX IF NOT EXISTS idx_event_reg_student 
ON event_registrations (event_id, student_id);

CREATE INDEX IF NOT EXISTS idx_event_dept_role 
ON event_registrations (event_id, department_id, role_id);

-- ฟังก์ชัน Atomic RPC: register_event_role
-- ป้องกัน Race Condition เมื่อ 60 คนแย่งกดตำแหน่งเดียวกันพร้อมกัน
CREATE OR REPLACE FUNCTION register_event_role(
  p_event_id TEXT,
  p_student_id TEXT,
  p_student_name TEXT,
  p_nickname TEXT,
  p_email TEXT,
  p_dept_id TEXT,
  p_dept_name TEXT,
  p_role_id TEXT,
  p_role_title TEXT,
  p_max_seats INT,
  p_note TEXT DEFAULT ''
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_event_status TEXT;
  v_occupied INT;
  v_existing_dept TEXT;
  v_existing_role TEXT;
  v_reg_id TEXT;
  v_result JSONB;
BEGIN
  -- 1. ตรวจสอบสถานะกิจกรรม
  SELECT status INTO v_event_status FROM events WHERE id = p_event_id;
  IF v_event_status IS NOT NULL AND v_event_status <> 'open' THEN
    RETURN jsonb_build_object('success', false, 'error', 'กิจกรรมนี้ปิดรับลงทะเบียนชั่วคราว');
  END IF;

  -- 2. ตรวจสอบตำแหน่งเดิมของนักศึกษา (ถ้ามี)
  SELECT department_id, role_id INTO v_existing_dept, v_existing_role
  FROM event_registrations
  WHERE event_id = p_event_id AND student_id = p_student_id;

  -- 3. ตรวจสอบจำนวนคนที่ลงในตำแหน่งนี้ (Lock แถวเพื่อนับโควตาแบบแม่นยำ)
  -- ถ้านักศึกษาลงตำแหน่งนี้อยู่แล้ว ไม่ต้องนับตัวเองเพิ่ม
  IF v_existing_dept IS NOT NULL AND v_existing_dept = p_dept_id AND v_existing_role = p_role_id THEN
    v_occupied := 0; -- ตัวเองอยู่ตำแหน่งนี้แล้ว ให้ผ่านได้เลย
  ELSE
    SELECT COUNT(*) INTO v_occupied
    FROM event_registrations
    WHERE event_id = p_event_id AND department_id = p_dept_id AND role_id = p_role_id;

    IF v_occupied >= p_max_seats THEN
      RETURN jsonb_build_object(
        'success', false, 
        'error', 'ขออภัย ตำแหน่งนี้มีผู้ลงทะเบียนเต็มจำนวนแล้ว (' || p_max_seats || '/' || p_max_seats || ' คน)'
      );
    END IF;
  END IF;

  -- 4. บันทึกข้อมูลลงทะเบียน (Upsert)
  v_reg_id := p_event_id || '_' || p_student_id;

  INSERT INTO event_registrations (
    id, event_id, student_id, student_name, nickname, email,
    department_id, department_name, role_id, role_title, note, registered_at
  ) VALUES (
    v_reg_id, p_event_id, p_student_id, p_student_name, p_nickname, p_email,
    p_dept_id, p_dept_name, p_role_id, p_role_title, p_note, NOW()
  )
  ON CONFLICT (id) DO UPDATE SET
    department_id = EXCLUDED.department_id,
    department_name = EXCLUDED.department_name,
    role_id = EXCLUDED.role_id,
    role_title = EXCLUDED.role_title,
    note = EXCLUDED.note,
    registered_at = NOW();

  v_result := jsonb_build_object(
    'success', true,
    'eventId', p_event_id,
    'studentId', p_student_id,
    'studentName', p_student_name,
    'departmentId', p_dept_id,
    'departmentName', p_dept_name,
    'roleId', p_role_id,
    'roleTitle', p_role_title
  );

  RETURN v_result;
END;
$$;

-- ================= 8. ตาราง USER_PROFILES (โปรไฟล์ อวาตาร์ และกรอบตกแต่งที่ซิงค์ทุกอุปกรณ์) =================
CREATE TABLE IF NOT EXISTS public.user_profiles (
  email TEXT PRIMARY KEY,
  student_id TEXT,
  name TEXT,
  nickname TEXT,
  phone TEXT,
  bio TEXT,
  line_id TEXT,
  instagram TEXT,
  facebook_url TEXT,
  avatar TEXT,
  avatar_frame TEXT DEFAULT 'none',
  avatar_anim TEXT DEFAULT 'none',
  avatar_transform JSONB DEFAULT '{"rotate": 0, "scale": 1, "flipX": false, "flipY": false}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read User Profiles" ON public.user_profiles;
CREATE POLICY "Public Read User Profiles" 
ON public.user_profiles FOR SELECT 
TO anon, authenticated 
USING (true);

DROP POLICY IF EXISTS "Allow Upsert User Profiles" ON public.user_profiles;
CREATE POLICY "Allow Upsert User Profiles" 
ON public.user_profiles FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow Update User Profiles" ON public.user_profiles;
CREATE POLICY "Allow Update User Profiles" 
ON public.user_profiles FOR UPDATE 
TO anon, authenticated 
USING (true)
WITH CHECK (true);

-- เปิด Realtime สำหรับตาราง user_profiles (ตรวจสอบก่อนเพิ่ม ป้องกัน Error 42710)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
      AND schemaname = 'public' 
      AND tablename = 'user_profiles'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.user_profiles;
  END IF;
END;
$$;

-- ข้อมูลรายชื่อนักศึกษาเริ่มต้น 60 คน (KKU COMED23)
INSERT INTO public.user_profiles (email, student_id, name, nickname, avatar, avatar_frame, avatar_anim)
VALUES
('kodchakon.sa@kkumail.com', '693050120-5', 'กชกร แสนอินทร์', 'มิวสิค', NULL, 'none', 'none'),
('kanokporn.kump@kkumail.com', '693050121-3', 'กนกพร คำพิทูล', 'โดนัท', NULL, 'none', 'none'),
('korakod.b@kkumail.com', '693050122-1', 'กรกต บรรเจิดวัฒนกุล', 'โนว่า', NULL, 'none', 'none'),
('kanchaniga.n@kkumail.com', '693050123-9', 'กัญชณิกา นันททิพักษ์', 'โบนัส', NULL, 'none', 'none'),
('kittichai.si@kkumail.com', '693050124-7', 'กิตติชัย สิงเนิน', 'น้ำเต้า', NULL, 'none', 'none'),
('kruithai.k@kkumail.com', '693050125-5', 'ขลุ่ยไทย เคนมี', 'ขลุ่ย', NULL, 'none', 'none'),
('jirathip.c@kkumail.com', '693050126-3', 'จิรทีปต์ ชัยศรี', 'บีน', NULL, 'none', 'none'),
('chaiyaphong.w@kkumail.com', '693050127-1', 'ชัยพงค์ วรรณทวี', 'มาร์ค', NULL, 'none', 'none'),
('thanchanok.sut@kkumail.com', '693050128-9', 'ธัญชนก สุตะโคตร', 'เค้ก', NULL, 'none', 'none'),
('thanyanan.su@kkumail.com', '693050129-7', 'ธันยนันท์ สุวัฒนะ', 'วาน', NULL, 'none', 'none'),
('theeradon.sr@kkumail.com', '693050130-2', 'ธีรดนย์ ศรีโพธิ์ชัย', 'ยูโร', NULL, 'none', 'none'),
('bunyarat.c@kkumail.com', '693050131-0', 'บุญญรัตน์ ชะนะพาล', 'อันอัน', NULL, 'none', 'none'),
('papada.ph@kkumail.com', '693050132-8', 'ปภาดา เพิ่มพูล', 'แตงโม', NULL, 'none', 'none'),
('punnamet.b@kkumail.com', '693050133-6', 'ปุณเมศ บุญสง', 'คิว', NULL, 'none', 'none'),
('phromphiriya.h@kkumail.com', '693050134-4', 'พรหมพิริยะ หอมจันทร์', 'โอปอน', NULL, 'none', 'none'),
('phitchaphon.d@kkumail.com', '693050135-2', 'พิชชาพร เดชกุล', 'แพนนี่', NULL, 'none', 'none'),
('phiraphat.ki@kkumail.com', '693050136-0', 'พีระพัฒน์ เกียมา', 'ต้นกล้า', NULL, 'none', 'none'),
('panuvich.k@kkumail.com', '693050137-8', 'ภาณุวิชญ์ ขัตติสอน', 'ไกด์', NULL, 'none', 'none'),
('phuthanet.wo@kkumail.com', '693050138-6', 'ภูธเนศ วงษ์ชาดี', 'ภู', NULL, 'none', 'none'),
('wacharaphol.i@kkumail.com', '693050139-4', 'วชรพล อินธิกาย', 'เนคไท', NULL, 'none', 'none'),
('wachirawit.sap@kkumail.com', '693050140-9', 'วชิรวิทย์ ทรัพย์เพิ่ม', 'นิว', NULL, 'none', 'none'),
('wachirawit.boonk@kkumail.com', '693050141-7', 'วชิรวิทย์ บุญขันธ์', 'คิว', NULL, 'none', 'none'),
('watcharakon.bu@kkumail.com', '693050142-5', 'วัชรากร บุญโสม', 'ออย', NULL, 'none', 'none'),
('sukollawat.p@kkumail.com', '693050143-3', 'ศุกลวัฒน์ พาพลงาม', 'เปรม', NULL, 'none', 'none'),
('athicha.pi@kkumail.com', '693050144-1', 'อธิชา พิมพ์ทอง', 'ไอคิว', NULL, 'none', 'none'),
('kemmanit.b@kkumail.com', '693050145-9', 'เขมนิจ บุตรชน', 'เขม', NULL, 'none', 'none'),
('panphitcha.k@kkumail.com', '693050146-7', 'เพ็ญพิชชา โกมลวรรค', 'นานา', NULL, 'none', 'none'),
('kaenpanom.c@kkumail.com', '693050157-5', 'แก่นพนม เฉลิมวงศ์วิวัฒน', 'ข้าวเหนียว', NULL, 'none', 'none'),
('sopitra.h@kkumail.com', '693050148-3', 'โสภิตรา หุนสุวงค์', 'เค้ก', NULL, 'none', 'none'),
('chatrada.k@kkumail.com', '693050383-3', 'ฉัตรรดา กะไรยะ', 'ฟ่าง', NULL, 'none', 'none'),
('chalakorn.k@kkumail.com', '693050384-1', 'ชลากร กุลสอนนาน', 'ต้น', NULL, 'none', 'none'),
('thitikan.boo@kkumail.com', '693050385-9', 'ฐิติกานต์ บุญสอน', 'มะปราง', NULL, 'none', 'none'),
('nattachai.p@kkumail.com', '693050386-7', 'ณัฏฐชัย โพธิ์ทับไทย', 'โอ้', NULL, 'none', 'none'),
('nichakhun.c@kkumail.com', '693050387-5', 'ณิชคุณ ชำนาญ', 'นาโน', NULL, 'none', 'none'),
('thanathip.p@kkumail.com', '693050388-3', 'ธนาธิป ภูนาเหนือ', 'ซี', NULL, 'none', 'none'),
('thitiwut.a@kkumail.com', '693050389-1', 'ธิติวุฒิ อารีเอื้อ', 'ภูผา', NULL, 'none', 'none'),
('thiraphon.b@kkumail.com', '693050390-6', 'ธีระพล บัวรัตน์', 'แม็กมิน', NULL, 'none', 'none'),
('prakrit.y@kkumail.com', '693050391-4', 'ประกฤษฎิ์ เหยียดชัยภูมิ', 'ต้นกล้า', NULL, 'none', 'none'),
('pichamon.sam@kkumail.com', '693050393-0', 'พิชามญธุ์ สามสี', 'หมูหวาน', NULL, 'none', 'none'),
('phuwakorn.m@kkumail.com', '693050394-8', 'ภูวกร มูลเหลา', 'เฟส', NULL, 'none', 'none'),
('ratchanon.saen@kkumail.com', '693050395-6', 'รัชชานนท์ แสงสว่าง', 'ภูมิ', NULL, 'none', 'none'),
('waranya.ar@kkumail.com', '693050396-4', 'วรัญญา อามาตย์', 'อุ้ม', NULL, 'none', 'none'),
('waritsara.ng@kkumail.com', '693050397-2', 'วริศรา งามประเสริฐ', 'นุ่น', NULL, 'none', 'none'),
('wimonsiri.w@kkumail.com', '693050398-0', 'วิมลสิริ วงศ์คำชาว', 'แพรวา', NULL, 'none', 'none'),
('wiraphat.phe@kkumail.com', '693050399-8', 'วีรภัทร เพชรอ้อม', 'ตะวัน', NULL, 'none', 'none'),
('sirawit.b@kkumail.com', '693050400-9', 'สิรวิชญ์ บุญหล้า', 'อั้ม', NULL, 'none', 'none'),
('benyapa.mee@kkumail.com', '693050401-7', 'เบญญาภา มีสวัสดิ์', 'บัวชมพู', NULL, 'none', 'none'),
('kanyarat.chaid@kkumail.com', '693050534-8', 'กัลยรัตน์ ไชยเดช', 'อเล็ก', NULL, 'none', 'none'),
('kttiphat.pi@kkumail.com', '693050535-6', 'กิตติพัฒน์ เพียรยิ่ง', 'ปอนด์', NULL, 'none', 'none'),
('thitipha.m@kkumail.com', '693050537-2', 'ทิติภา มาสุข', 'ดีดี้', NULL, 'none', 'none'),
('pharida.d@kkumail.com', '693050538-0', 'ภริดา เด่นไชยรัตน์', 'ต้นอ้อ', NULL, 'none', 'none'),
('poommarin.b@kkumail.com', '693050539-8', 'ภูมรินทร์ บุญมี', 'ภูมิ', NULL, 'none', 'none'),
('ronnachai.sa@kkumail.com', '693050540-3', 'รณชัย สายเนตร์', 'น็อต', NULL, 'none', 'none'),
('adsadakorn.s@kkumail.com', '693050541-1', 'อัษฎากร ศรีสังข์', 'บาส', NULL, 'none', 'none'),
('chitsanupong.sae@kkumail.com', '693050562-3', 'ชิษณุพงศ์ แสงสีงาม', 'ไผ่', NULL, 'none', 'none'),
('tharathip.ka@kkumail.com', '693050563-1', 'ธาราทิพย์ การร้อย', 'บีม', NULL, 'none', 'none'),
('punyaphat.s@kkumail.com', '693050564-9', 'ปุณยพัฒน์ สินโพธิ์', 'โบนัส', NULL, 'none', 'none'),
('phiyada.san@kkumail.com', '693050565-7', 'พิยดา สารทอง', 'โซอี้', NULL, 'none', 'none'),
('suthikan.b@kkumail.com', '693050566-5', 'สุธีกานต์ บัตเลอร์', 'เจสซี่', NULL, 'none', 'none'),
('apassara.n@kkumail.com', '693050567-3', 'อาภัสรา นากลาง', 'เป้ย', NULL, 'none', 'none')
ON CONFLICT (email) DO NOTHING;

-- ================= 9. ตาราง SHORTLINKS (ระบบย่อลิงก์ & QR Code พร้อมรหัสผ่านและสถิติคลิก) =================
CREATE TABLE IF NOT EXISTS public.shortlinks (
  id TEXT PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  target_url TEXT NOT NULL,
  category TEXT DEFAULT 'ทั่วไป',
  clicks INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  password_hash TEXT,
  expires_at TIMESTAMPTZ,
  click_stats JSONB DEFAULT '{"devices":{},"browsers":{},"referrers":{},"daily":{}}'::jsonb,
  qr_settings JSONB DEFAULT '{}'::jsonb,
  notes TEXT,
  created_by TEXT DEFAULT 'ผู้ดูแลระบบ',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ปรับเพิ่มคอลัมน์ใหม่หากสร้างไว้ก่อนแล้ว
ALTER TABLE public.shortlinks ADD COLUMN IF NOT EXISTS password_hash TEXT;
ALTER TABLE public.shortlinks ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
ALTER TABLE public.shortlinks ADD COLUMN IF NOT EXISTS click_stats JSONB DEFAULT '{"devices":{},"browsers":{},"referrers":{},"daily":{}}'::jsonb;
ALTER TABLE public.shortlinks ADD COLUMN IF NOT EXISTS qr_settings JSONB DEFAULT '{}'::jsonb;

ALTER TABLE public.shortlinks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read shortlinks" ON public.shortlinks;
CREATE POLICY "Allow public read shortlinks" 
ON public.shortlinks FOR SELECT 
TO anon, authenticated 
USING (true);

DROP POLICY IF EXISTS "Allow public insert shortlinks" ON public.shortlinks;
CREATE POLICY "Allow public insert shortlinks" 
ON public.shortlinks FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update shortlinks" ON public.shortlinks;
CREATE POLICY "Allow public update shortlinks" 
ON public.shortlinks FOR UPDATE 
TO anon, authenticated 
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public delete shortlinks" ON public.shortlinks;
CREATE POLICY "Allow public delete shortlinks" 
ON public.shortlinks FOR DELETE 
TO anon, authenticated 
USING (true);

-- เปิด Realtime สำหรับตาราง shortlinks
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
      AND schemaname = 'public' 
      AND tablename = 'shortlinks'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.shortlinks;
  END IF;
END;
$$;



