/**
 * =========================================================================
 * SUPABASE SECURITY RULES & ROW LEVEL SECURITY (RLS) POLICIES
 * สคริปต์ SQL ป้องกันการเจาะระบบฐานข้อมูล Supabase สำหรับ COMED KKU 69
 * =========================================================================
 * 
 * วิธีนำไปใช้งาน:
 * 1. เปิดเว็บ Supabase Dashboard (https://supabase.com/dashboard)
 * 2. เข้าโปรเจกต์ของคุณ -> ไปที่เมนู "SQL Editor" ด้านซ้ายมือ
 * 3. กด "New Query" แล้วคัดลอกคำสั่งด้านล่างนี้ทั้งหมดไปวาง
 * 4. กดปุ่ม "Run" เพื่อเปิดเกราะป้องกันทันที!
 */

-- 1. สร้างตารางที่จำเป็นในระบบอัตโนมัติ (หากยังไม่มีในฐานข้อมูล)
CREATE TABLE IF NOT EXISTS admin_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  admin_email TEXT,
  action TEXT,
  detail TEXT
);

CREATE TABLE IF NOT EXISTS campaigns (
  id TEXT PRIMARY KEY,
  code TEXT,
  title TEXT NOT NULL,
  subtitle TEXT,
  category TEXT,
  amount NUMERIC(10, 2) DEFAULT 0,
  currency TEXT DEFAULT 'THB',
  deadline TIMESTAMPTZ,
  deadline_display TEXT,
  bank_name TEXT,
  account_number TEXT,
  account_name TEXT,
  qr_image TEXT,
  slip_provider TEXT DEFAULT 'cloudinary',
  status TEXT DEFAULT 'open',
  closed_reason TEXT,
  is_default BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. เปิดใช้งาน Row Level Security (RLS) บนทุกตารางหลัก
ALTER TABLE IF EXISTS payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS admin_logs ENABLE ROW LEVEL SECURITY;

-- 3. เคลียร์นโยบายเก่าออกก่อนเพื่อป้องกันการสร้างซ้ำ
DROP POLICY IF EXISTS "Public Read Payments" ON payments;
DROP POLICY IF EXISTS "Public Insert Payments" ON payments;
DROP POLICY IF EXISTS "Deny Public Delete Payments" ON payments;
DROP POLICY IF EXISTS "Public Read Campaigns" ON campaigns;
DROP POLICY IF EXISTS "Allow Insert Campaigns" ON campaigns;
DROP POLICY IF EXISTS "Allow Update Campaigns" ON campaigns;
DROP POLICY IF EXISTS "Allow Insert Admin Logs" ON admin_logs;
DROP POLICY IF EXISTS "Deny Delete Admin Logs" ON admin_logs;

-- ================= 4. ตาราง PAYMENTS (ข้อมูลการชำระเงินและสลิป) =================
-- อนุญาตให้อ่านข้อมูลได้ (เพื่อเช็ครายชื่อและสถิติการจ่าย)
CREATE POLICY "Public Read Payments" 
ON payments FOR SELECT 
TO anon, authenticated 
USING (true);

-- อนุญาตให้แนบสลิปส่งยอดเงินได้
CREATE POLICY "Public Insert Payments" 
ON payments FOR INSERT 
TO anon, authenticated 
WITH CHECK (
  student_id IS NOT NULL 
  AND length(student_id) >= 8 
  AND amount > 0
);

-- ห้ามคนทั่วไปสั่ง DELETE ลบสลิปในฐานข้อมูลทิ้ง
CREATE POLICY "Deny Public Delete Payments" 
ON payments FOR DELETE 
TO anon 
USING (false);

-- ================= 5. ตาราง CAMPAIGNS (รายการเก็บเงินและตั้งค่าเว็บ) =================
-- อนุญาตให้อ่านข้อมูลแคมเปญได้ทุกคน (เพื่อให้หน้าเว็บแสดงยอดและ QR Code)
CREATE POLICY "Public Read Campaigns" 
ON campaigns FOR SELECT 
TO anon, authenticated 
USING (true);

-- อนุญาตให้บันทึก / สร้าง / อัปเดตข้อมูลแคมเปญได้ (แก้ Error 403 / Access Control Checks ตอน Upsert)
CREATE POLICY "Allow Insert Campaigns" 
ON campaigns FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

CREATE POLICY "Allow Update Campaigns" 
ON campaigns FOR UPDATE 
TO anon, authenticated 
USING (true)
WITH CHECK (true);

-- ================= 6. ตาราง ADMIN LOGS (ประวัติการกระทำ) =================
CREATE POLICY "Allow Insert Admin Logs" 
ON admin_logs FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

CREATE POLICY "Deny Delete Admin Logs" 
ON admin_logs FOR DELETE 
TO anon 
USING (false);
